### PR TITLE
Giving kiwisdr an ability to run with reverse proxy

### PR DESCRIPTION
**Pull request by lazywalker**
Many people can't get a dedicated IP from their ISP, which means they can't run any web service from their home cable network, that makes running a public kiwisdr is not possible.
I'm try to find a way to do that job, currently i have [frp](https://github.com/fatedier/frp) with an remote server(outside my home), that works fine, except all client IPs in Admin panel are always 127.0.0.1, so i made a minor change to the code to fix this issue and so far so good.

My testing station using frp proxy: http://szsdr.vicp.io:8073

### CODE REVIEW

**Comment by lazywalker** [comment]
after applied this patch the kiwi can only handle 2 users online and keep saying server is full, what do i miss?

**Comment by jks-prv** [comment]
I'm on holiday and Internet is expensive here. I can check the "server full" problem on 6 Aug when I get home. Is vicp.io just a hosting site where you run an instance of frps?

**Comment by jks-prv** [comment]
Tell me more about your experience using the commented out check for the header "X-Forwarded-For". That was actually suggested back in January in this issue: https://github.com/jks-prv/Beagle_SDR_GPS/issues/85

I suppose this would catch proxies that send it and not X-Real-IP? I did some reading and it seems you'd have to parse the first ip in case the proxy ip addresses are also sent, viz: "X-Forwarded-For: client, proxy1, proxy2 ..."

**Comment by jks-prv** [comment]
Okay, I just pushed a change to eliminate the "only 2 online users" problem.

The X-header code had to be moved earlier before the sound/waterfall connection matching code so they are comparing the same ip addresses.

**Comment by lazywalker** [comment]
Great job John!
I try the latest fix it works with no problem. Hope i didn't ruin your holiday. :)

**Pull request merged**
