### PR TITLE
Automatically detecting the upstream repo

### PR DESCRIPTION
**Pull request by burundiocibu**
This work removes the hard-coded references to jks-prv's GitHub repo, allowing a user to point to a personal repo and still have the auto-update code work. I did this work around v1.7 and have been merging in changes from jks-prv/Beagle_SDR_GPS into TomGaussiran/Beagle_SDR_GPS since. The changes seem to be working well.

### CODE REVIEW

**Comment by burundiocibu** [comment]
BTW, @TomGaussiran and I work together. I believe he has told you about our build of the KiWi.

**Comment by jks-prv** [comment]
Hi Jon. Yes, I've been wondering how you guys have been doing with the Kiwis you built.

These changes are interesting. There has long been this comment at the bottom of the update tab on the admin page: "TODO: alt github name". But detecting the repository of the clone is not something I had considered. My understanding of how git works is limited. The last source control system I was really familiar with was SCCS more than 30 years ago. Probably before some of you were born, lol.

I know it's been working fine for you, but I need to check it myself since it has the possibility of bricking the update process. I have bricked the 10 beta Kiwis in the past and it was no fun recovering from that. I still don't have an independent mechanism that can roll-back to a previous version in case of bricking.

**Comment by burundiocibu** [comment]
Totally understand that it needs close scruteny. I'll be glad to help in any way if you see something that doesn't look quit right.

**Comment by burundiocibu** [comment]
Hold off looking at this merge request. I've created another branch on @TomGaussiran repo  and merged the update.cpp conflicts. Let me test that a bit before updating Tom's master.

**Comment by burundiocibu** [comment]
Just submitted a new merge request so I'm closing this one out.

**Pull request closed without merging**
