### PR TITLE
IBP_scan addition of automated waterfall image saves

### PR DESCRIPTION
**Pull request by GeoNomad**
requested by W1EUJ

tested on iPad by G8JNJ

### CODE REVIEW

**Comment by jks-prv** [comment]
Once again, why are you putting these in your source code?
`kiwi_check_js_version.push({ VERSION_MAJ:1, VERSION_MIN:146, file:'extensions/IBP_scan/IBP_scan.js' });
`
Doing this will brick all 2000+ Kiwi's worldwide when update 147 is released. The only way to recover is for every Kiwi owner to ssh into the Beagle and force an update manually! Many will not know how and I'll have the worst support nightmare imaginable.

Are you getting these by copying javascript from the browser debugger window? These are dynamically appended to each .js file as they are served by the Kiwi and **do not** appear anywhere in the source code.

**Comment by jks-prv** [comment]
Alright, it was relatively easy to add a button to the dialog so you can continue even if the check fails.

mismatch copy 2

**Comment by GeoNomad** [comment]
Sorry, I assumed you would remove the version lines when you merged the files.

I need the lines to test the code with the current version (for the same reason they cause a problem with the next version), so it is an indication of what version I tested with and thought that might be of use to you. I don't recall you mentioning them before. I will delete them in future but I haven't made a point of looking at these comments in the past.

Thanks for putting up with my quirks.

**Comment by GeoNomad** [comment]
Hi John, I've been away for a while. I am updating the IBP_scan and waterfall functions to take into account the new rate features. Were there any other problems that prevented you from merging a couple of weeks ago, or were you just busy with other features?

**Comment by jks-prv** [comment]
I'm just busy. I'm in the middle of moving house, visitors for Xmas, magazine article deadlines, dozens of emails/messages/posts per day, a major UI upgrade..

**Comment by GeoNomad** [comment]
At least you're not bored. Take care.

**Comment by jks-prv** [comment]
I'll get to it just as soon as I possibly can.

**Comment by GeoNomad** [comment]
I closed it because I have moved forward since then with additions that take into account the new features on the waterfall. I will create a new pull request after testing on various browsers. Martin is checking on the iPad...

**Pull request closed without merging**
