### PR TITLE
Make mkcolormap readable.

### PR DESCRIPTION
**Pull request by rikvanriel**
The function was indented so strangely that it was barely readable.
Change to a human-readable indentation, to make it easier to tweak
the waterfall scheme, should anyone want that.

Yes, I am investigating whether I can make weak signals more visible
in the waterfall. Why do you ask?

### CODE REVIEW

**Comment by jks-prv** [comment]
Fixing my use of tabs is on the bug list. I was properly chastised by Andrew Holme for incorrectly using tabs in the source such that it becomes unreadable when browsing on Github. I should set my editor to do tab-to-space expansion instead. But I need to be careful when doing the conversion not to make things worse.

**Comment by rikvanriel** [comment]
I actually put tabs in to indent this code, not knowing of any github issues with tabs. The github code viewer seems to render it just fine when I browse to the function in question.

**Comment by jks-prv** [comment]
I should go back and look at Andrew's email, but I think his arguments is that tabs are bad because you don't know how they are interpreted by a third-party viewer. You might have intended tab stops to means 4 spaces (I do), but other viewers (e.g. Github) might do something else.

**Comment by icm7216** [comment]
mkcolormap() tab stops has using 3, maybe.
Please try this, add `?ts=3` to the github-repo-code-url. that shows at 3 tab stops. See: [mkcolormap()](https://github.com/jks-prv/Beagle_SDR_GPS/blob/c6028a9626966b5c915d3e9a90b4d0b992f545ed/web/openwebrx/openwebrx.js?ts=3#L2406)

like this:
mkcolormap

**Pull request merged**
