### PR TITLE
Added frequency memory - up/down arrows

### PR DESCRIPTION
**Pull request by GeoNomad**
Added past 25 frequencies in memory accessed by up/down arrows on
frequency box.
Save memories to cookies.

Hopefully resolved github conflicts!

### CODE REVIEW

**Comment by jks-prv** [comment]
Had to push a change passing 'event' to freq_keydown(). How did this ever work for you?

**Comment by jks-prv** [comment]
I'm not sure how I feel about the UI implications of this.

I'll bet money we get complaints. Something like "the frequency box changes but the actual rx frequency doesn't". Others will disagree and want the confirming <cr>. An argument could be made these should be in (yet another) menu. But the control panel UI is already too cluttered.

**Comment by GeoNomad** [comment]
UI is always tricky when things get complicated. I didn't pass the event to freq_keydown() because I wanted the Enter confirmation - which is the normal UI on DOS or other command-line methods. Nothing happens until you accept the change. In general, you can test my code on my kiwisdr.ve3sun.com:8073 receiver to see if you like it. Just because I write some code, I don't expect you to always agree it should become part of the standard product.

**Comment by GeoNomad** [comment]
The other method would be to make the frequency a combo-box, with the history in the pull-down. I like this better, but didn't want to make the change this time. Something to experiment with later.

**Pull request merged**
