### PR TITLE
Include Makefile from ../extensions/* and ../extensions/*/extensions/*

### PR DESCRIPTION
**Pull request by dl3led**
Sorry, I screwed the previous version when trying to rebase to current state of original repo.
Now I'm using a different branch for this change.

### CODE REVIEW

**Comment by jks-prv** [comment]
Yeah, so I really don't want to do this.

Including ../extensions/*/Makefile is unnecessary. I know the ant_switch still has a Makefile there with a definition for FILES_EMBED. But that Makefile is no longer referenced by the Kiwi build process (it needs to be removed). External extension .js and .css files are loaded dynamically rather than being compiled into the in-memory filesystem. If your extension contains more files than just _ext_name_.js and _ext_name_.css then you need to add the file paths in a call to kiwi_load_js_dir(). See web/extensions/fsk/fsk.js for an example.

I don't want to add a wildcard include of ../extensions/*/extensions/*/Makefile to the Kiwi Makefile because that makes the Kiwi build process very vulnerable to failures in the external environment. Which creates a support burden on me by being difficult to debug. Right now the Kiwi Makefile does the absolute minimum by scanning the external extension directories for _ext_name_.cpp and not much else. If you want to do something fancy with a makefile it should be done at the time your extension is manually installed. Not called on every single Kiwi build.

**Comment by dl3led** [comment]
Thanks for your hints about kiwi_load_js_dir.
But in my case it's not about JavaScript. I need to make use of an external library in the C code.

This is what I had to put in my Makefile:
LIBS+= -L/usr/local/lib -lmosquitto

Any idea how to accomplish that without including the Makefile in the build process?

**Comment by dl3led** [comment]
Bootstrap problem: using "dlopen" requires "Link with -ldl." (see `man dlopen`) :-(

**Comment by jks-prv** [comment]
So this is a very bad idea. Calling an external third-party package on the Beagle side can have unknown real-time implications for the Kiwi code (with disastrous consequences). If any of the stuff is doing Linux system calls that have even a few tens-of-milliseconds of unexpected delay the Kiwi audio will break. You need to be doing all your own stuff at a very low, predictable level where you can figure out what's going wrong when things break. And also have minimal impact on me and my support burden which is already beyond breaking point. I'm just not going to start linking in random libraries into the Kiwi binary at this point. I don't need anymore headaches.

**Comment by dl3led** [comment]
I understand your concerns. But that's exactly why I would like to be able to offload all these functions from the KiwiSDR to a separate system, e. g. a Raspberry Pi. 

But to do this I need some means of communication between the extension and the external system, and to me MQTT sounds much more suitable for this purpose than any other protocol, because it just passes tiny messages _asynchronously_, and thus should have _much less_ performance impact on the Kiwi than other solutions that make system calls to call shell scripts or fork additional tasks each time an action is required (like ant_switch or the prototype code I built so far) or even http/REST based protocols.

All I need is some way to to make this external communication via MQTT possible, and that requires linking to an MQTT client library. The easiest way would be to include `../extensions/*/extensions/*/Makefile`, or otherwise include `-ldl` in the link flags to allow for dynamic loading.

**Pull request closed without merging**
